- codeApproach.md
Created the first version of the coding approach.Will keep updating it as we will progress
> 01 coding approach v1

- README.md
- user-persona2.md
> 08 user persona 2

- README.md
- user-persona1.md
Added the first user-persona: Health-conscious consumer
> 07 user persona 1

- .vscode/settings.json
- README.md
- planning/1-communication-plan.md
- planning/2-constraits.md
- create a new branch `10-planning `
- create and complete the `Communication Plan` with the team
- create and complete the `Constraints ` with the team
> add planning files

- package-lock.json
- package.json
- src/app/globals.css
- src/app/page.js
- src/app/page.module.css
- Some commits were not pushed so this is an update for this branch
> 11 header v1

- package-lock.json
- package.json
- src/app/components/Footer.css
- src/app/components/Footer.js
- src/app/page.js
> adding footer component

- src/app/components/Footer.css
- src/app/components/Footer.js
- src/app/components/Header.js
- src/app/components/NavBar.js
- src/app/components/slideShow.js
- src/app/page.js
> 36 maintenance

- src/app/components/SlideShow.module.css
- src/app/components/slideShow.js
> add some change to style

- src/app/components/SingleRecipe/SingleRecipe.js
added  RapidAPI-Key header in my component as well.
> single recipe

- src/app/components/FilterComponent/Filter.css
- src/app/components/NavBar.css
> fix navbar styling

- src/app/components/FilterComponent/Filter.js
- src/app/components/FilterComponent/MenuOrigin.js
- src/app/components/FilterComponent/ShowRecipes.js
- src/app/components/Header.js
- src/app/components/NavBar.js
- src/app/components/RandomRecipe/SingleRecipe.css
- src/app/components/RandomRecipe/SingleRecipe.js
> Add home button to navbar and logo

- src/app/components/Footer.css
- src/app/components/SlideShow.js
- src/app/components/SlideShow.module.css
> footer and slide Show issue 

- src/app/components/SlideShow.js
- src/app/components/SlideShow.module.css
> back to home page issue

- src/app/components/Favorites/FavoriteRecipes.js
- src/app/components/Favorites/RecipeCard.js
- src/app/components/Favorites/page.css
- src/app/components/Favorites/page.js
- src/app/components/FilterComponent/RecipeCard.css
- src/app/components/FilterComponent/RecipeCard.js
- src/app/components/NavBar.css
- src/app/components/NavBar.js
- src/app/components/RandomRecipe/SingleRecipe.js
- src/app/components/SingleRecipe/SingleRecipe.css
- src/app/components/SingleRecipe/SingleRecipe.js
- src/app/services/Firebase.js
> 28 wishlist v3

- src/app/components/FilterComponent/page.js
> fix the navbar issue

- src/app/components/SingleRecipe/SingleRecipe.js
- src/app/components/SingleRecipe/UpdateRating.js
> updating user ratingg

- src/app/components/about/about.css
Adapting about page for the mobile devices
> adapt about

- src/app/components/terms/terms.css
Adapting terms of use page for the mobile devices
> adapt terms

- src/app/components/NavBar.js
> fix navbar toggle

- src/app/components/Favorites/page.js
- src/app/components/FilterComponent/Filter.js
- src/app/components/FilterComponent/Paginate.css
- src/app/components/FilterComponent/Paginate.js
- src/app/components/FilterComponent/ShowRecipes.css
- src/app/components/FilterComponent/ShowRecipes.js
- src/app/components/FilterComponent/page.js
- src/app/components/Header.js
- src/app/components/RandomRecipe/page.js
- src/app/components/SingleRecipe/SingleRecipe.js
- src/app/components/SlideShow.module.css
- src/app/components/terms/terms.css
- src/app/page.js
> fix show-recipes component

- src/app/components/FilterComponent/Filter.css
- src/app/components/FilterComponent/Filter.js
> Improve the fillters display on mobile

- src/app/components/Favorites/RecipeCard.css
- src/app/components/Favorites/RecipeCard.js
- src/app/components/Favorites/page.css
- src/app/components/Favorites/page.js
> add styling to favorites

- src/app/components/SingleRecipe/SingleRecipe.css
- src/app/components/SingleRecipe/SingleRecipe.js
- src/app/components/SlideShow.js
- src/app/components/SlideShow.module.css
fix the slider mobile version issue
> fix the slider mobile version issue

- src/app/components/FilterComponent/MenuOrigin.js
> change for to htmlFor

- package-lock.json
- package.json
- src/app/components/SingleRecipe/SingleRecipe.css
- src/app/components/SingleRecipe/SingleRecipe.js
- src/app/components/SingleRecipe/UpdateRating.js
- src/app/components/SlideShow.js
- src/app/components/SlideShow.module.css
> 26 rating v3

- src/app/components/SingleRecipe/ShowRating.js
- src/app/components/SingleRecipe/UpdateRating.js
Did small fix for rating component.
> firebase call fix
